In [1]:
# Load an image, print shape, pixel values, channels, and explain them

from PIL import Image
import numpy as np

img = Image.open("image_as_number.jpg")

img_arr = np.array(img)

print("Image Shape:", img_arr.shape)

h, w, c = img_arr.shape

print("Height:", h)
print("Width:", w)
print("Channels:", c)

print("\nFirst Pixel Value:")
print(img_arr[0, 0])

print("\nSample Pixel Values:")
print(img_arr[:5, :5])

Image Shape: (980, 1749, 3)
Height: 980
Width: 1749
Channels: 3

First Pixel Value:
[199 213 214]

Sample Pixel Values:
[[[199 213 214]
  [199 213 214]
  [200 214 215]
  [200 214 215]
  [200 214 215]]

 [[199 213 214]
  [199 213 214]
  [199 213 214]
  [199 213 214]
  [200 214 215]]

 [[198 212 213]
  [198 212 213]
  [198 212 213]
  [199 213 214]
  [199 213 214]]

 [[198 212 213]
  [198 212 213]
  [198 212 213]
  [198 212 213]
  [199 213 214]]

 [[198 212 213]
  [198 212 213]
  [198 212 213]
  [199 213 214]
  [199 213 214]]]
